services:
  # MGNREGA API Server
  - type: web
    name: mgnrega-api
    env: node
    region: singapore
    plan: free
    # Root directory is current folder (server code is at root of this repo)
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
